name: bf-tideprediction
channels:
  - CONDA_CHANNEL
dependencies:
  - click=6.6
  - coverage=4.2
  - decorator=4.0.10
  - dill=0.2.5
  - Flask=0.11.1
  - Flask-WTF=0.12
  - gunicorn=19.6.0
  - itsdangerous=0.24
  - Jinja2=2.8
  - MarkupSafe=0.23
  - nose=1.3.7
  - numpy=1.14.0=py27_blas_openblas_200
  - scipy=0.18.0
  - six=1.10.0
  - Werkzeug=0.11.10
  - WTForms=2.1
  - WTForms-Components=0.10.0
  - flask-wtf-alchemy-utils=0.1.0
  - infinity=1.4
  - intervals=0.8.0
  - WTForms-Alchemy=0.16.1
  - SQLAlchemy=1.0.14
  - SQLAlchemy-Utils=0.32.9
  - validators=0.11.0
  - pytides=0.0.4
