sudo ym install pip
sudo pip install numpy
sudo pip install Shapely
sudo pip install pytides
sudo pip install json
sudo pip install nose
sudo pip install flask
sudo pip install flask-login
sudo pip install flask-wtf
